app/models/history.py
from datetime import datetime
from . import db

class History(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    result = db.Column(db.String(50), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    uid = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    
    def __init__(self, result, uid):
        self.result = result
        self.uid = uid
        self.date = datetime.utcnow()

app/controllers/dataController.py
import os
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from models.user import User, db
from models.history import History
import subprocess;
import tensorflow as tf
import pandas as pd
import sys
import json
import re
from tensorflow import keras
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from flask_migrate import Migrate
import matplotlib.pyplot as plt
from utils import gen_grafico, gen_grafico2, ejecutar_script, borrar_graficos

dataController = Blueprint('dataController', __name__, template_folder='templates')

@dataController.route('/procesar', methods=['POST', 'GET'])
@login_required
def procesar():
    """
    Procesa un archivo enviado por el usuario y muestra los resultados.
    ---
    tags:
        - Data
    parameters:
      - name: archivo
        in: formData
        type: file
        required: true
        description: Archivo (formato .txt o .csv) a procesar.

    responses:
      200:
        description: Resultados del procesamiento mostrados correctamente.
        schema:
          type: object
          properties:
            titulo:
              type: string
              description: Título de la página
            cont:
              type: integer
              description: Contador inicializado en 1
            archivo:
              type: string
              description: Ruta del archivo generado (imagen)
            probabilidades:
              type: object
              description: Resultados de probabilidades generados
    """


    if request.method == 'POST':
        if 'archivo' not in request.files:
            return redirect(url_for('index'))

        archivo = request.files['archivo'] 
        if archivo and (archivo.filename.endswith('.txt') or archivo.filename.endswith('.csv')):
            archivo_path = os.path.join('csv', archivo.filename)
            archivo.save(".\\csv\\"+archivo.filename)
            resultado_script = ejecutar_script(archivo_path)
            print(resultado_script)
            probabilidades = gen_grafico(resultado_script)
            res = History(result=str(probabilidades), uid=current_user.id)
            db.session.add(res)
            db.session.commit()
            data = {
                'titulo': 'Resultado del script',	
                'cont': 1,
                'archivo': 'img/grafico.png',
                'probabilidades': probabilidades
            }
            return render_template("index.html", data = data)

        return 'Formato de archivo no permitido. Por favor, sube un archivo .txt o .csv.'

@dataController.route('/history/<int:history_id>', methods=['POST', 'GET', 'DELETE'])
@login_required
def history_details(history_id):
    """
    Obtiene los detalles del historial especificado por su ID.
    ---
    tags:
        - Data
    parameters:
      - name: history_id
        in: path
        type: integer
        required: true
        description: ID del historial a obtener.

    responses:
      200:
        description: Detalles del historial obtenidos correctamente.
        schema:
        type: object
        properties:
            titulo:
              type: string
              description: Título de la página
            historial:
              type: object
              description: Detalles del historial
            archivo:
              type: string
              description: Ruta del archivo generado (imagen)
            probabilidades:
              type: object
              description: Resultados de probabilidades generados
      404:
        description: Historial no encontrado.
    """

    historial = History.query.get_or_404(history_id)
    
    resultado_script = json.loads(historial.result)
    probabilidades = gen_grafico2(resultado_script)

    data = {
        'titulo': 'Detalles del Historial',
        'historial': historial,
        'archivo': 'static/img/grafico.png',
        'probabilidades': probabilidades,
    }

    return render_template('history_details.html', data=data)


@dataController.route('/history')
@login_required
def history():
    """
    Obtiene el historial de procesamientos del usuario actual.
    ---
    tags:
        - Data
    responses:
      200:
        description: Historial obtenido correctamente.
        schema:
        type: object
        properties:
            titulo:
              type: string
              description: Título de la página
            historiales:
              type: array
              items:
                type: object
                properties:
                id:
                    type: integer
                    description: ID del historial
                result:
                    type: string
                    description: Resultado del procesamiento
                uid:
                    type: integer
                    description: ID del usuario
    """


    borrar_graficos()
    historiales = History.query.filter_by(uid=current_user.id).all()
    print(historiales)
    data={
        'historiales': historiales,
        'titulo': 'Historial'
    }
    return render_template('history.html', data=data)

@dataController.route('/history/delete/<int:history_id>', methods=['POST', 'GET', 'DELETE'])
@login_required
def delete_history(history_id):
    """
    Elimina un historial especificado por su ID.
    ---
    tags:
        - Data
    parameters:
      - name: history_id
        in: path
        type: integer
        required: true
        description: ID del historial a eliminar.

    responses:
      200:
        description: Historial eliminado correctamente.
      404:
        description: Historial no encontrado.
    """

    historial = History.query.get_or_404(history_id)
    db.session.delete(historial)
    db.session.commit()
    return redirect(url_for('dataController.history'))

app/controllers/userController.py
import os
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from models.user import User, db
from models.history import History
import subprocess;
import tensorflow as tf
import pandas as pd
import sys
import json
import re
from tensorflow import keras
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from flask_migrate import Migrate
import matplotlib.pyplot as plt
from utils import gen_grafico, gen_grafico2, ejecutar_script, borrar_graficos

userController = Blueprint('userController', __name__, template_folder='templates')



@userController.route('/register', methods=['GET', 'POST'])
def register():
    """
    Registro de un nuevo usuario.
    ---
    tags:
      - User
    get:
      description: Muestra la página de registro de usuario.
      responses:
        200:
          description: Página de registro mostrada correctamente.

    post:
      description: Registra un nuevo usuario.
      parameters:
      - name: username
        in: formData
        type: string
        required: true
        description: Nombre de usuario.
      - name: password
        in: formData
        type: string
        required: true
        description: Contraseña del usuario.
      - name: confirm_password
        in: formData
        type: string
        required: true
        description: Confirmación de la contraseña del usuario.
      - name: name
        in: formData
        type: string
        required: true
        description: Nombre completo del usuario.
      - name: email
        in: formData
        type: string
        required: true
        description: Correo electrónico del usuario.
    responses:
        200:
          description: Usuario registrado con éxito.
        400:
          description: Error en los datos de entrada.
        409:
          description: Conflicto, el usuario o el correo electrónico ya existen.
    """

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        name = request.form['name']
        email = request.form['email']

        if(password != confirm_password):
            flash('Las contraseñas no coinciden.', 'error')
            return redirect(url_for('userController.register'))

        email_regex = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        if not re.match(email_regex, email):
            flash('El formato del correo electrónico no es válido.', 'error')
            return redirect(url_for('userController.register'))
        
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash('El usuario ya existe.', 'error')
            return redirect(url_for('userController.register'))

        existing_email = User.query.filter_by(email=email).first()
        if existing_email:
            flash('El correo electrónico ya está en uso.', 'error')
            return redirect(url_for('userController.register'))

        hashed_password = generate_password_hash(password)
        new_user = User(username=username, password=hashed_password, name=name, email=email)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('userController.login'))
    return render_template('register.html')

@userController.route('/login', methods=['GET', 'POST'])
def login():
    """
    Inicia sesión en el sistema.
    ---
    tags:
       - User
    get:
      description: Muestra la página de inicio de sesión.
      responses:
        200:
        description: Página de inicio de sesión mostrada correctamente.

    post:
      description: Inicia sesión con las credenciales proporcionadas.
      parameters:
      - name: username
        in: formData
        type: string
        required: true
        description: Nombre de usuario.
      - name: password
        in: formData
        type: string
        required: true
        description: Contraseña del usuario.
    responses:
        200:
          description: Inicio de sesión exitoso.
        400:
          description: Credenciales incorrectas o error en los datos de entrada.
    """
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('index'))
        else:
            flash('Login fallido. Por favor, verifica tus credenciales.', 'error')
    data={
        'titulo': 'Inicio de sesión',
    }
    return render_template('login.html', data=data)

@userController.route('/logout', methods=['POST'])
@login_required
def logout():
    """
    Cierra la sesión del usuario actual.
    ---
    tags:
      - User
    post:
      description: Cierra la sesión del usuario actual.
      responses:
        200:
          description: Sesión cerrada con éxito.
        401:
          description: No autorizado, el usuario no ha iniciado sesión.
    """


    borrar_graficos()
    logout_user()
    return redirect(url_for('userController.login'))

@userController.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    """
    Recuperación de contraseña.
    ---
    tags:
      - User
    get:
      description: Muestra la página de recuperación de contraseña.
      responses:
        200:
        description: Página de recuperación de contraseña mostrada correctamente.

    post:
      description: Permite al usuario recuperar su contraseña.
      parameters:
      - name: email
        in: formData
        type: string
        required: true
        description: Correo electrónico del usuario.
      - name: new_password
        in: formData
        type: string
        required: true
        description: Nueva contraseña del usuario.
      - name: confirm_new_password
        in: formData
        type: string
        required: true
        description: Confirmación de la nueva contraseña del usuario.
    responses:
        200:
          description: Contraseña recuperada con éxito.
        400:
          description: Error en los datos de entrada.
        404:
          description: No se encontró ningún usuario con ese email.
    """

    if request.method == 'POST':
        email = request.form['email']
        user = User.query.filter_by(email=email).first()
        
        if not user:
            flash('No se encontró ningún usuario con ese email.', 'error')
            return redirect(url_for('userController.forgot_password'))

        new_password = request.form['new_password']
        confirm_new_password = request.form['confirm_new_password']

        if(new_password != confirm_new_password):
            flash('Las contraseñas no coinciden.', 'error')
            return redirect(url_for('userController.forgot_password'))

        user.password = generate_password_hash(new_password)
        db.session.commit()

        return redirect(url_for('userController.login'))
    
    return render_template('forgot_password.html')

@userController.route('/profile', methods=['POST', 'GET'])
@login_required
def profile():
    """
    Perfil del usuario.
    ---
    tags:
      - User
    get:
      description: Muestra la página del perfil del usuario.
      responses:
        200:
          description: Página del perfil mostrada correctamente.
        401:
          description: No autorizado, el usuario no ha iniciado sesión.
    post:
      description: Actualiza la información del perfil del usuario.
      responses:
        200:
          description: Información del perfil actualizada correctamente.
        400:
          description: Error en los datos de entrada.
        401:
          description: No autorizado, el usuario no ha iniciado sesión.
    """

    data={
        'titulo': 'Perfil',
        'usuario': current_user
    }
    return render_template('profile.html', data=data)

@userController.route('/update_profile', methods=['POST', 'GET'])
@login_required
def update_profile():
    """
    Actualiza la información del perfil del usuario.
    ---
    tags:
      - User
    get:
      description: Muestra la página de actualización del perfil del usuario.
      responses:
        200:
          description: Página de actualización del perfil mostrada correctamente.
        401:
          description: No autorizado, el usuario no ha iniciado sesión.

    post:
      description: Actualiza la información del perfil del usuario.
      parameters:
      - name: name
        in: formData
        type: string
        required: true
        description: Nombre del usuario.
      - name: password
        in: formData
        type: string
        required: false
        description: Nueva contraseña del usuario (opcional).
      - name: confirm_password
        in: formData
        type: string
        required: false
        description: Confirmación de la nueva contraseña del usuario (opcional).
    responses:
        200:
          description: Información del perfil actualizada correctamente.
        400:
          description: Error en los datos de entrada.
        401:
          description: No autorizado, el usuario no ha iniciado sesión.
    """

    if request.method == 'POST':
        current_user.name = request.form['name']

        password = request.form['password']
        confirm_password = request.form['confirm_password']
        if(password and confirm_password):
            if(password != confirm_password):
                flash('Las contraseñas no coinciden.', 'error')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/history.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css')}}">
    <script src="{{ url_for('static', filename='js/index.js')}}"></script>
    <script src="https://kit.fontawesome.com/681de42033.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>{{data.titulo}}</title>
</head>
<body>
    <div class="header">
        <div class="nav-div">
            <nav>
                <a href="{{ url_for('index') }}">Inicio</a>
                <a href="{{ url_for('dataController.history') }}">Historial</a>
            </nav>
        </div>
        <div class="buttons">
            {% if current_user.is_authenticated %}
                <form action="{{ url_for('userController.logout') }}" method="POST">
                    <input type="submit" value="Cerrar sesión">
                </form>
            {% endif %}
            {% if not current_user.is_authenticated %}
            <div class="auth-buttons">
                <form action="{{ url_for('userController.login') }}" method="GET">
                    <input type="submit" value="Iniciar sesión">
                </form>
                <form action="{{ url_for('userController.register') }}" method="GET">
                    <input type="submit" value="Registrarse">
                </form>
            </div>
            {% endif %}
            
            <form action = "{{ url_for('userController.profile') }}" method="GET">
                <button class="fa-solid fa-user icon fa-3x profile-button" onclick="{{ url_for('userController.profile') }}" >
            </form>
        </div>

    </div>


    <div class="page-content">
        {% block contenido %}
        {% endblock %}
    </div>

</body>
</html>

app/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css')}}">
    <title>Recuperar Contraseña</title>
</head>
<body>
    <div class="login-div">
        <h2>Recuperar contraseña</h2>
        <form action="{{ url_for('userController.forgot_password') }}" method="POST" class="login-form">
            <div class="form-field">
                <label for="username">Nombre de usuario:</label><br>
                <input type="text" id="username" name="username" required><br>
            </div>
            <div class="form-field">
                <label for="email">Correo Electrónico:</label><br>
                <input type="email" id="email" name="email" required><br>
            </div>
            <div class="form-field">
                <label for="new_password">Contraseña:</label><br>
                <input type="password" id="new_password" name="new_password" required><br>
            </div>
            <div class="form-field">
                <label for="confirm_new_password">Confirma Contraseña:</label><br>
                <input type="password" id="confirm_new_password" name="confirm_new_password" required><br>
            </div>
                <!-- Mostrar mensaje de error -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'error' %}
                                <div class="error-message">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <!-- Fin de mensaje de error -->
            <input type="submit" value="Recuperar" class="button">
        </form>

    </div>
</body>

app/templates/history.html
{% extends './base.html' %}

{% block contenido %}
<div class="page-content">
    <h1>Historial</h1>
    <div class="table-div">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Resultado</th>
                    <th>Fecha</th>
                    <th>Detalles</th>
                </tr>
            </thead>
            <tbody>
                {% for historial in data.historiales %}
                        <tr>
                            <td>{{ historial.id }}</td>
                            <td>{{ historial.result }}</td>
                            <td>{{ historial.date }}</td>
                            <td>
                                <a href="{{ url_for('dataController.history_details', history_id=historial.id) }}" class="btn btn-info">Detalles</a>
                            </td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/history_details.html
{% extends './base.html' %}

{% block contenido %}
<div class="result-div">

    <div class="result">
        <h2>Resultado</h2>
        <p>
            <div class="data_results">
                <img src="{{ url_for('static', filename='img/grafico.png') }}" alt="Gráfico de Barras">
                <div class="probabilities">
                    {% for prob in data.probabilidades %}
                        Clase {{ loop.index }}: {{ prob }}<br>
                    {% endfor %}
                </div>
            </div>
        </p>
    </div>
    <div class="delete-button">
        <form action="{{ url_for('dataController.delete_history', history_id=data.historial.id) }}" method="POST">
            <input type="hidden" name="user_id" value="{{ current_user.id }}">
            <button type="submit" class="del-history-button">Eliminar Elemento</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends './base.html' %}

{% block contenido %}


<div class="upload-div">
    <div class="upload-container">
        <h2>Subir Archivo</h2>
        <form action="{{ url_for('dataController.procesar') }}" method="post" enctype="multipart/form-data">
            <input type=file name=archivo>
            <input type=submit value=Subir>
        </form>
    </div>
</div>


<div class="result-div">

    <div class="result">
        <h2>Resultado</h2>
        <p>
            {% if data.cont == 1 %}

                <div class="data_results">
                    <img src="{{ url_for('static', filename='img/grafico.png') }}" alt="Gráfico de Barras">
                    <div class="probabilities">
                        {% if data.probabilidades %}
                            {% for prob in data.probabilidades %}
                                Clase {{ loop.index }}: {{ prob }}<br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </p>
    </div>

</div>

{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css')}}">
    <title>{{data.titulo}}</title>
</head>
<body>
    <div class="login-div">
        <h2>Iniciar sesión</h2>
        <form action="{{ url_for('userController.login') }}" method="POST" class="login-form">
            <div class="form-field">
                <label for="username">Nombre de usuario:</label><br>
                <input type="text" id="username" name="username" required><br>
            </div>
            <div class="form-field">
                <label for="password">Contraseña:</label><br>
                <input type="password" id="password" name="password" required><br>
            </div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'error' %}
                                <div class="error-message">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            <input type="submit" value="Iniciar sesión" class="button">
        </form>
        <div class="buttons">
                <a href="{{ url_for('userController.register') }}" class="button">Registrarse</a>

                <a href="{{ url_for('userController.forgot_password') }}" class="button fp-button">He olvidado la contraseña</a>
        </div>

    </div>
</body>

app/templates/profile.html
{% extends './base.html' %}

{% block contenido %}
    <div class="profile-div">
        <h2>Perfil</h2>
        <label>Nombre de Usuario: {{ current_user.username }}</label><br>
        <label>Correo Electrónico:{{ current_user.email }}</label>
        <form action="{{ url_for('userController.update_profile') }}" method="POST" class="profile-form">
            <div class="form-field">
                <label>Nombre:</label>
                <input type="text" id="name" name="name" value={{ current_user.name }}>
            </div>
            <div class="form-field">
                <label>Cambiar contraseña</label>
                <input type="password" id="password" name="password">
            </div>
            <div class="form-field">
                <label>Confirmar contraseña</label>
                <input type="password" id="confirm_password" name="confirm_password">
            </div>
            <input type="submit" value="Actualizar" class="button">

        </form>
        <form action="{{ url_for('userController.delete_user') }}" method="POST">
            <input type="hidden" name="user_id" value="{{ current_user.id }}">
            <button type="submit" class="button del-button">Eliminar Usuario</button>
        </form>
    </div>

    
{% endblock %}

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css')}}">
    <title>Registro de Usuario</title>
</head>
<body>
    <div class="register-div">
        <h2>Registro</h2>
        <form action="{{ url_for('userController.register') }}" method="POST">
            <div class="form-field"> 
                <label for="username">Nombre de Usuario:</label><br>
                <input type="text" id="username" name="username" required><br>
            </div>

            <div class="form-field"> 
                <label for="name">Nombre:</label><br>
                <input type="text" id="name" name="name" required><br>
            </div>

            <div class="form-field"> 
                <label for="email">Correo Electrónico:</label><br>
                <input type="email" id="email" name="email" required><br>
            </div>

            <div class="form-field"> 
                <label for="password">Contraseña:</label><br>
                <input type="password" id="password" name="password" required><br>
            </div>
            <div class="form-field"> 
                <label for="confirm-password">Confirma Contraseña:</label><br>
                <input type="password" id="confirm_password" name="confirm_password" required><br>
            </div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'error' %}
                                <div class="error-message">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            <input type="submit" value="Registrarse" class="button">
        </form>
        <p>¿Ya tienes una cuenta? <a href="{{ url_for('userController.login') }}">Iniciar sesión</a></p>
    </div>
    

</body>
</html>